### ISSUE TITLE
npm 2.x + Docker = spawn .../mozjpeg/vendor/cjpeg ENOENT error

### ISSUE THREAD

**Issue by mikkotikkanen** [imagemin/imagemin-mozjpeg#14]
When running imagemin-mozjpeg in Docker (I suspect any linux) with npm 2.x
`spawn ../imagemin-mozpeg/node_modules/mozjpeg/vendor/cjpeg ENOENT` error is produced.

Quickly looking at this it looks like something like this happens:
With npm 2.x it tries to look for the vendor directory under `../imagemin-mozjpeg/node_modules/mozjpeg`, which for some reason or not is not there. However, when switching to npm 3.x, it looks for the mozjpeg directly under main node_modules, where the vendor directory does exist.

**Comment by shinnn** [comment]
You've already obtained the answer. When you just mount all built files to the Docker container instead of rebuilding the app inside the container, you should use the same npm version on both Docker container and your local machine.

**Comment by mikkotikkanen** [comment]
Err. Are you seriously proposing of using Windows binaries in Docker?
