### ISSUE TITLE
Does not work with npm 2.x + Docker

### ISSUE THREAD

**Issue by mikkotikkanen** [imagemin/imagemin-mozjpeg#15]
I don't know why the previous issue was closed and locked, as this is (or at least should be) a proper issue.

Just tested one more time - With npm 2.x (which comes with the latest node.js LTS release, v. 4.4.7), no optimizations can be done, instead the following error is triggered.:

    Error: spawn /usr/src/app/node_modules/imagemin-mozjpeg/node_modules/mozjpeg/vendor/cjpeg ENOENT

It appears that the `/mozjpeg/vendor` directory is not properly built under `/imagemin-mozjpeg/node_modules`, thus the error is triggered. However, if `mozjpeg` is added to the dependencies of the project, the module appears to work, which is similar to what happens with npm 3.x, since it tries to flatten the directory tree. However, this also means that `imagemin-mozjpeg` could break if different version of `mozjpeg` is included with the project already, which is when module child dependencies would be installed similarly to npm 2.x.

It was suggested in previous issue that I should use same binaries from host OS but since I'm running Windows, I can not and regardless one _should not_ use same binaries from the host OS. Even node.js official onbuild Dockerfiles does separate install per container for a reason.

**Comment by shinnn** [comment]
This plugin just works fine on npm 2.x + Linux. https://travis-ci.org/imagemin/imagemin-mozjpeg/jobs/126655558#L132
