### ISSUE TITLE
Fails to install on Windows 7

### ISSUE THREAD

**Issue by sridi** [imagemin/imagemin-mozjpeg#20]
npm install --save imagemin-mozjpeg throws:

> npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DELL\\AppData\\
Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "imagemin-m
ozjpeg"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

> npm ERR! mozjpeg@4.1.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mozjpeg@4.1.1 postinstall script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mozjpeg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mozjpeg
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mozjpeg
npm ERR! There is likely additional logging output above.

**Comment by shinnn** [comment]
Don't use obsolete Windows 7. Just upgrade to the latest version.

**Comment by lbod** [comment]
@shinnn did you mean upgrade the OS to win 8 or later? Some can't do that, especially in corporate type environments.

There doesn't seem to be much information on binary/os dependencies for any of the imagemin plugins, it's difficult especially if you're trying to build for more than one os.
