### ISSUE TITLE
Quality in version 6

### ISSUE THREAD

**Issue by matthewdolman** [imagemin/imagemin-mozjpeg#21]
I have been using version 5.1 for some time and an image of 1mb can be reduced to about 30kb @ quality = 50.

When I upgrade to 6.0.0  the same settings output a file about 350kb

**Comment by yesworld** [comment]
Maybe my issue #35 is related to yours. But I couldn't run script in the 5.1 version. :(

**Comment by 1000ch** [comment]
This seems not to be a problem with this package.
