### ISSUE TITLE
Quality option does not work under Windows

### ISSUE THREAD

**Issue by michel-kraemer** [imagemin/imagemin-mozjpeg#3]
It seems `mozjpeg-bin` uses `jpegtran.exe` under Windows which does not seem to accept a `-quality` argument. Is there something I can do about it?

Thanks,
Michel

**Comment by kevva** [comment]
https://github.com/imagemin/mozjpeg-bin/issues/7

**Comment by michel-kraemer** [comment]
Thanks a lot. It happens under Ubuntu as well by the way.

Michel

**Comment by kevva** [comment]
Yes, it's because we haven't published a new release yet. Still waiting on a Windows binary.

**Comment by shinnn** [comment]
@michel-kraemer Would you mind building mozjpeg 3.0 on Windows and creating a pull request?

**Comment by michel-kraemer** [comment]
Yes, I will try and get back to you.

**Comment by michel-kraemer** [comment]
This was easier than I thought. Now it's up to you to integrate it :smile: Thanks for all the work!

Cheers,
Michel

**Comment by maranomynet** [comment]
imagemin-mozjpeg is still ingnores the `quality` setting on Windows.
Any movement on this?

**Comment by shinnn** [comment]
@kevva @sindresorhus `npm owner add shinnn imagemin-mozjpeg`, please. I want to publish v5.0.0 to npm.

**Comment by sindresorhus** [comment]
@shinnn done :)

**Comment by shinnn** [comment]
@sindresorhus Thanks!

Just published imagemin-mozjpeg 5.0.0 which uses mozjpeg 3.0.0 and supports its options.

**Comment by sindresorhus** [comment]
:beers:

**Comment by kevva** [comment]
:beers:
