### ISSUE TITLE
Update deps to solve vulnerable report

### ISSUE THREAD

**Issue by evilebottnawi** [imagemin/imagemin-mozjpeg#33]
/cc @sindresorhus Will be great to do this as in `imagemin-pngquant`. I can send PR.

**Comment by rejas** [comment]
https://github.com/imagemin/imagemin-mozjpeg/pull/34 hopefully fixes it, but we need somebody to finally merge it. @sindresorhus or whoever still listens in this group, please allow us to fix this.....
