### ISSUE TITLE
Error Installing Plugin Grunt 0.4.5

### ISSUE THREAD

**Issue by dsoldera** [imagemin/imagemin-mozjpeg#5]
Hi there,

I was trying to install this plugin on Grunt 0.4.5 version, but I can't. Some problems with fstream.

Please check the print screen attached.

![error-imagemin-mozjpeg-stream](https://cloud.githubusercontent.com/assets/11474555/8522538/7e4391e6-23c5-11e5-9d47-e91b7d0cc2a4.png)

Could you please check it?

Thanks.

**Comment by shinnn** [comment]
You're using ancient Node and npm. Retry installation after upgrading them.

**Comment by shinnn** [comment]
Your error log is very similar to npm/npm#8058's.

**Comment by kevva** [comment]
Going to close this. Will open if your problem persists.
