### ISSUE TITLE
mtime is not updated causing gulp-changed/gulp-newer to fail

### ISSUE THREAD

**Issue by noderat** [imagemin/imagemin-mozjpeg#6]
It appears that the mtime of files passed through mozjpeg is not updated, so gulp-changed (or gulp-newer) can't detect if there are newer files.

**Comment by shinnn** [comment]
Can you show us your gulpfile?

**Comment by noderat** [comment]
Here's a snippet:
```javascript
gulp.task(function mozjpeg() {
  var mozjpeg = require('imagemin-mozjpeg');
  return gulp.src(path.join(config.src, '**/*.{jpg,jpeg}'))
    .pipe(changed(config.dest))
    .pipe(mozjpeg(config.mozjpeg.options)())
    .pipe(debug({title: 'mozjpeg:'}))
    .pipe(gulp.dest(config.dest));
  });
```

**Comment by noderat** [comment]
So I checked mtime/atime between imagemin-mozjpeg and a plugin that was working (ttf2woff) and it appears that neither updates the mtime, but ttf2woff is updating the atime. Now I'm confused.

**Comment by shinnn** [comment]
I guess this issue is not directly related to this plugin. However, if you create a small repository by which we can reproduce the problem, I'll check it when I have a time.

**Comment by noderat** [comment]
So after doing some testing I was able to determine that this is caused by using the gulp 4.0 branch. Is there some option in [gulpjs/gulp#4.0](https://github.com/gulpjs/gulp/tree/4.0) that I'm missing?

**Comment by shinnn** [comment]
Hmm, I haven't try gulp 4 yet and probably gulp team can help you better. https://github.com/gulpjs/gulp/issues Hope you find the root cause.
