### ISSUE TITLE
Option to allow converting to JPEG from non-JPEG input formats

### ISSUE THREAD

**Issue by niieani** [imagemin/imagemin-mozjpeg#7]
Currently all non-jpeg images are filtered out by:
```js
		if (!isJpg(file.contents)) {
			cb(null, file);
			return;
		}
```
However, mozjpeg binary supports other input formats, such as PNG.
It would be great to have a convert option that does not filter other image formats.

**Comment by sindresorhus** [comment]
Out of scope for this plugin. Imagemin is about minifying images. You can just use the underlying binary directly: https://github.com/imagemin/mozjpeg-bin

**Comment by tomasklaen** [comment]
Is this still out of scope? Because `imagemin-webp` accepts jpg and png no problem.

**Comment by niieani** [comment]
Yes, that was my original point. I didn't mean we should add some new layer to convert thins prior to passing them through to `mozjpeg`, just to not have a guard against whether `mozjpeg` already supports today.
